// ─────────────────────────────────────────────────────────────
// 탭1 공고 목데이터. JobPostingTable.tsx 안에 있던 것을 그대로 옮겼다(2026-07-29).
// 값은 한 글자도 바꾸지 않았다 — 실제 API가 붙으면 이 파일만 지우면 된다.
// ─────────────────────────────────────────────────────────────
import { calcDday } from "@/lib/dday";
import type { Job } from "./jobTypes";

export const initialJobData: Job[] = [
  {
    id: "j1",
    slug: "naver",
    company: "네이버",
    title: "프론트엔드 개발자",
    role: "프론트엔드",
    employType: "신입",
    industry: "IT/테크",
    deadline: "2026-07-01",
    dday: calcDday("2026-07-01"),
    status: "작성중",
    finalResult: null,
    linked: { schedules: 1, todos: 2 },
    starred: false,
    updatedAt: "2시간 전",
    registeredAt: "2026-06-15",
    stage: "작성중",
  },
  {
    id: "j2",
    slug: "kakao",
    company: "카카오",
    title: "백엔드 엔지니어",
    role: "백엔드",
    employType: "신입",
    industry: "IT/테크",
    deadline: "2026-07-05",
    dday: calcDday("2026-07-05"),
    status: "작성중",
    finalResult: null,
    linked: { schedules: 2, todos: 1 },
    starred: true,
    updatedAt: "3시간 전",
    registeredAt: "2026-06-16",
    stage: "작성중",
  },
  {
    id: "j3",
    slug: "toss",
    company: "토스",
    title: "Product Designer",
    role: "디자인",
    employType: "인턴",
    industry: "핀테크",
    deadline: "2026-06-30",
    dday: calcDday("2026-06-30"),
    status: "작성중",
    finalResult: null,
    linked: { schedules: 1, todos: 3 },
    starred: true,
    updatedAt: "1시간 전",
    registeredAt: "2026-06-18",
    stage: "작성중",
  },
  {
    id: "j4",
    slug: "samsung",
    company: "삼성전자",
    title: "SW 엔지니어",
    role: "풀스택",
    employType: "신입",
    industry: "제조/전자",
    deadline: "2026-07-10",
    dday: calcDday("2026-07-10"),
    status: "지원완료",
    finalResult: null,
    linked: { schedules: 0, todos: 1 },
    starred: false,
    updatedAt: "어제",
    registeredAt: "2026-06-10",
    stage: "지원완료",
  },
  {
    id: "j5",
    slug: "coupang",
    company: "쿠팡",
    title: "데이터 분석가",
    role: "데이터",
    employType: "경력",
    industry: "이커머스",
    deadline: "2026-06-15",
    dday: calcDday("2026-06-15"),
    status: "전형완료",
    finalResult: "불합격",
    linked: { schedules: 0, todos: 0 },
    starred: false,
    updatedAt: "3일 전",
    registeredAt: "2026-05-20",
    stage: "전형완료",
    completedAt: "2026-06-15",
  },
  {
    id: "j6",
    slug: "line",
    company: "라인",
    title: "iOS 개발자",
    role: "모바일",
    employType: "신입",
    industry: "IT/테크",
    deadline: "2026-07-07",
    dday: calcDday("2026-07-07"),
    status: "면접전형",
    finalResult: null,
    linked: { schedules: 1, todos: 0 },
    starred: false,
    updatedAt: "5일 전",
    registeredAt: "2026-06-05",
    stage: "면접전형",
  },
];
